### ISSUE TITLE
sublime.set_timeout_async(lambda:os.system(BIN + ARG), 0)

### ISSUE THREAD

**Issue by flashjay** [FloydaGitHub/RunQuickSimulator#1]
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./RunQuickSimulator.py", line 119, in run
    launch_simulator(file_name)
  File "./RunQuickSimulator.py", line 111, in launch_simulator
    sublime.set_timeout_async(lambda:os.system(BIN + ARG), 0)
AttributeError: 'module' object has no attribute 'set_timeout_async'

**Comment by flashjay** [comment]
Mac平台
SublimeText 2

这个函数只在 SublimeText3 下才能使用？

**Comment by flashjay** [comment]
好吧，这个函数 2 不支持：
https://www.sublimetext.com/docs/2/api_reference.html
